# (PART\*) Linear models in `R` {-}

# Learning objectives

**Summary :** In this workshop, you will learn the structure of a linear model and its different variants such as simple regression, analysis of variance (ANOVA), analysis of covariance (ANCOVA) and multiple regression. This workshop focuses on implementing linear models in R with `lm()` and `anova()`, identifying models that do not meet the conditions for application and solving problems.

# Preparing for the workshop

All workshop materials are found at [github.com/QCBSRworkshops/workshop04](https://github.com/QCBSRworkshops/workshop04). This includes an [R script](https://qcbsrworkshops.github.io/workshop04/book-en/workshop04-script-en.R) which contains all code chunks shown in this book.

For this workshop, we will be working with the following datasets:

* [birdsdiet](http://qcbs.ca/wiki/_media/birdsdiet.csv)
* [dickcissel](http://qcbs.ca/wiki/_media/dickcissel.csv)

> To download this data, do right click + save on the page that opens.

You should also make sure you have downloaded, installed, and loaded these packages:

* [dplyr](https://cran.r-project.org/package=dplyr) (to work with data)
* [vegan](https://cran.r-project.org/package=vegan) (for population data analyses)
* [e1071](https://cran.r-project.org/package=e1071) (to test models)
* [MASS](https://cran.r-project.org/package=MASS) (for linear discriminant analysis)
* [car](https://cran.r-project.org/package=car) (for the analysis of variance)
* [effect](https://cran.r-project.org/package=effect) (to visualize models)