# (PART\*) Modèles linéaires en `R` {-}

# Objectifs d'apprentissage

**Résumé :** Dans cet atelier, vous apprendrez la structure d'un modèle linéaire et ses différentes variantes telles que la régression simple, l'analyse de variance (ANOVA), l'analyse de covariance (ANCOVA) et la régression multiple. Cet atelier se concentre sur l'application de modèles linéaires dans R avec `lm()` et `anova()`, sur l'identification de modèles dont les conditions d'application ne sont pas rencontrées et sur régler les problèmes.

# Préparez-vous pour cet atelier

Tout le matériel de l'atelier se trouve sur [github.com/QCBSRworkshops/workshop04](https://github.com/QCBSRworkshops/workshop04). Cela inclut un [script R](https://qcbsrworkshops.github.io/workshop04/book-fr/workshop04-script-fr.R) qui rassemble tous les morceaux de code présentés dans ce livre.

Pour cet atelier, nous travaillerons avec les jeux de données suivants :

* [birdsdiet](http://qcbs.ca/wiki/_media/birdsdiet.csv)
* [dickcissel](http://qcbs.ca/wiki/_media/dickcissel.csv)

> Pour télécharger ces données, faites un clic droit + enregistrer sur la page qui s'ouvre.

Vous devriez également vous assurer d'avoir téléchargé, installé et chargé les librairies R suivantes:

* [dplyr](https://cran.r-project.org/package=dplyr) (pour travailler avec les données)
* [vegan](https://cran.r-project.org/package=vegan) (pour l'analyse de données populationnelles)
* [e1071](https://cran.r-project.org/package=e1071) (pour tester les modèles)
* [MASS](https://cran.r-project.org/package=MASS) (pour l’analyse discriminante linéaire)
* [car](https://cran.r-project.org/package=car) (pour l'analyse de variance)
* [effect](https://cran.r-project.org/package=effect) (pour la visualisation de modèles)

```
# Installez les paquets requis
install.packages(c('dplyr', 'vegan', 'e1071', 'MASS', 'car', 'effect'))

# Chargez les paquets requis
library(dplyr)
library(vegan)
library(e1071)
library(MASS)
library(car)
library(effect)
```
