# (PART\*) Considérations finales {-}

Vous êtes maintenant prêts à effectuer des régressions, des
ANOVA et des ANCOVA sur vos propres données. Cependant, rappelez-vous de
toujours spécifier vos modèles correctement et de vérifier leurs
conditions de base avant d'interpréter les résultats en fonction des
caractéristiques écologiques de vos données.

# Résumé

Le modèle linéaire décrit la relation entre une variable **réponse** et une ou plusieurs autres variables **prédictrices**. Elle est utilisée pour analyser une **hypothèse bien formulée**, souvent associée à une question de recherche plus générale. La régression détermine si les variables sont correllées en inférent la **direction** et la **force** d'une relation, et notre **confiance** dans les estimations de l'effet.

Lors du prochaine atelier, vous verrez comment programmer en R. Vous apprendrez à utiliser des structures de contrôle (boucles `for`, `if`, `while`) afin d'éviter la répétition de code, de faciliter l'organisation et d'effectuer des simulations. Vous apprendrez également à écrire vos propres fonctions et quelques astuces pour programmer plus efficacement.

# Resources additionnels

#### Aides mémoire (*cheat sheets*)


------------------------------------------------------------------------

#### Quelques livres

-   Myers RH - Classical and Modern Regression with Application
-   Gotelli NJ - A Primer of Ecological Statistics

------------------------------------------------------------------------

#### Quelques sites internet

